
image: Visual Studio 2019

clone_depth: 3

platform:
  - x64

configuration:
  - Release
  
matrix:
  fast_finish: false

init:
  - cmd: cmake --version

install:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - echo Building tinyxml2
  - git clone https://github.com/leethomason/tinyxml2.git
  - cd tinyxml2 
  - mkdir build
  - cd build
  - cmake -Dtinyxml2_SHARED_LIBS:BOOL=ON -DCMAKE_INSTALL_PREFIX=../../usr ..
  - cmake --build . --config Release --target ALL_BUILD
  - cmake --install .
  - cd ../..
  
before_build:
  - cmake -D Qt5_DIR=C:\Qt\5.15.2\msvc2019_64\lib\cmake\Qt5 ..

build_script:
  - cmake --build . --config Release -- %MSBUILD_ARGS%
